blank_issues_enabled: true
contact_links:
  - name: Self-serve Request
    url: https://github.com/testground/github-mgmt/edit/master/github/testground.yml
    about: Propose a GitHub configuration change by modifying testground.yml
