blank_issues_enabled: true
contact_links:
  - name: PR
    url: https://github.com/testground/github-mgmt/edit/master/github/testground.yml
    about: Propose GitHub configuration change by modifying testground.yml
